---
- name: Make sure the mount points of the buckets are present
  become: yes
  file:
    path: "{{ item.mountpoint }}"
    state: directory
  with_items: "{{ buckets }}"
  ignore_errors: yes
  no_log: True

- name: Add start/stop script
  become: yes
  template:
    src: s3fs.j2
    dest: /etc/init.d/s3fs
    mode: 0755
  notify: restart s3fs

- name: Add s3fs to run levels
  become: yes
  service:
    name: s3fs
    enabled: yes

- name: Make sure mountpoints are present in fstab
  become: yes
  mount:
    name: "{{ item.mountpoint }}"
    src: "s3fs#{{ item.bucket }}"
    fstype: fuse
    opts: "_netdev,{{ item.options }}"
    state: present
  with_items: "{{ buckets }}"
  when: buckets is defined
